### ISSUE TITLE
Broken in 3.5?

### ISSUE THREAD

**Issue by frioux** [lammermann/awesome-configs#3]
So I see that you have converted this to awesome 3.5, but something seems really messed up.  When I use this (if you are interested take a look at https://github.com/frioux/dotfiles/blob/awesome-3.5/awesome/rc.lua) I see the taglist only in the main monitor.  All of the other monitors have no associated tag list.  I tried checking out and using your config directly and experienced the exact same issue.

I'm using Ubuntu 15.10; here is the output of `awesome --version`:

```
awesome v3.5.6 (For Those About To Rock)
 • Build: Sep  1 2015 11:28:53 for x86_64 by gcc version 5.2.1 (buildd@lgw01-18)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
```

Please let me know if there is anything else I can do to help resolve this.  I really love sharetags and would hate to stop using it.

**Comment by solodkiy** [comment]
This lib not work for me in awesome 3.5.5 
I made fork for fix this.
Perhaps it will help you: https://github.com/XLegion/sharetags

**Comment by frioux** [comment]
Yeah, @XLegion is right and this fixes my issue pretty well.
